{{- if eq .Values.mode "enterprise" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terry.fullname" . }}-secrets
  labels:
    {{- include "terry.labels" . | nindent 4 }}
type: Opaque
stringData:
  tfc-token: {{ .Values.tfcToken | quote }}
{{- end }}