apiVersion: v1
kind: Service
metadata:
  name: {{ include "terry.fullname" . }}
  labels:
    {{- include "terry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web-ui
      protocol: TCP
      name: web-ui
    - port: {{ .Values.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "terry.selectorLabels" . | nindent 4 }}