#!/bin/bash
echo "=== Environment Check ==="
echo "Current directory: $(pwd)"
echo "User: $(whoami)"
echo "PATH: $PATH"
echo ""
echo "=== Terraform Tools ==="
which terraform || echo "terraform not found"
terraform version 2>/dev/null || echo "terraform not available"
echo ""
echo "=== Terraform LSP ==="
which terraform-ls || echo "terraform-ls not found"
terraform-ls version 2>/dev/null || echo "terraform-ls not available"
echo ""
echo "=== Container Info ==="
cat /etc/os-release 2>/dev/null | head -3 || echo "OS info not available"
