apiVersion: v1
kind: Service
metadata:
  name: terry-form-mcp
  namespace: terry-form-mcp
spec:
  selector:
    app: terry-form-mcp
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
